<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estimas</title>
</head>
<body>
    <style>
        table, th, td {
            border: 1px solid black !important;
            border-collapse: collapse !important;
        }

        table{
            width: 100%;
            margin-bottom: 35px;
        }
    </style>
    <main>
        <div>
            <table>
                <thead>
                    <tr>
                        <th>Horario</th>
                        <th>Lunes</th>
                        <th>150</th>
                        <th>$</th>
                        <th>200</th>
                        <th>$</th>
                        <th>250</th>
                        <th>$</th>
                        <th>300</th>
                        <th>$</th>
                        <th>350</th>
                        <th>$</th>
                        <th>400</th>
                        <th>$</th>
                        <th>450</th>
                        <th>$</th>
                        <th>500</th>
                        <th>$</th>
                        <th>Total</th>
                        <th>TA</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($lunes as $dataEstima)
                    <tr>
                        <td></td>
                        <td>{{$dataEstima->nombreMunicipio}}</td>
                        <td>{{$dataEstima->nPrimerPrestamo}}</td>
                        <td>{{$dataEstima->montoPrimerPrestamo}}</td>
                        <td>{{$dataEstima->nSegundoPrestamo}}</td>
                        <td>{{$dataEstima->montoSegundoPrestamo}}</td>
                        <td>{{$dataEstima->nTercerPrestamo}}</td>
                        <td>{{$dataEstima->montoTercerPrestamo}}</td>
                        <td>{{$dataEstima->nCuartoPrestamo}}</td>
                        <td>{{$dataEstima->montoCuartoPrestamo}}</td>
                        <td>{{$dataEstima->nQuintoPrestamo}}</td>
                        <td>{{$dataEstima->montoQuintoPrestamo}}</td>
                        <td>{{$dataEstima->nSextoPrestamo}}</td>
                        <td>{{$dataEstima->montoSextoPrestamo}}</td>
                        <td>{{$dataEstima->nSeptimoPrestamo}}</td>
                        <td>{{$dataEstima->montoSeptimoPrestamo}}</td>
                        <td>{{$dataEstima->nOctavoPrestamo}}</td>
                        <td>{{$dataEstima->montoOctavoPrestamo}}</td>
                        <td>{{$dataEstima->totalMonto}}</td>
                        <td>{{$dataEstima->totalAbonos}}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <div>
            <table>
                <thead>
                    <tr>
                        <th>Horario</th>
                        <th>Martes</th>
                        <th>150</th>
                        <th>$</th>
                        <th>200</th>
                        <th>$</th>
                        <th>250</th>
                        <th>$</th>
                        <th>300</th>
                        <th>$</th>
                        <th>350</th>
                        <th>$</th>
                        <th>400</th>
                        <th>$</th>
                        <th>450</th>
                        <th>$</th>
                        <th>500</th>
                        <th>$</th>
                        <th>Total</th>
                        <th>TA</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($martes as $dataEstima)
                    <tr>
                        <td></td>
                        <td>{{$dataEstima->nombreMunicipio}}</td>
                        <td>{{$dataEstima->nPrimerPrestamo}}</td>
                        <td>{{$dataEstima->montoPrimerPrestamo}}</td>
                        <td>{{$dataEstima->nSegundoPrestamo}}</td>
                        <td>{{$dataEstima->montoSegundoPrestamo}}</td>
                        <td>{{$dataEstima->nTercerPrestamo}}</td>
                        <td>{{$dataEstima->montoTercerPrestamo}}</td>
                        <td>{{$dataEstima->nCuartoPrestamo}}</td>
                        <td>{{$dataEstima->montoCuartoPrestamo}}</td>
                        <td>{{$dataEstima->nQuintoPrestamo}}</td>
                        <td>{{$dataEstima->montoQuintoPrestamo}}</td>
                        <td>{{$dataEstima->nSextoPrestamo}}</td>
                        <td>{{$dataEstima->montoSextoPrestamo}}</td>
                        <td>{{$dataEstima->nSeptimoPrestamo}}</td>
                        <td>{{$dataEstima->montoSeptimoPrestamo}}</td>
                        <td>{{$dataEstima->nOctavoPrestamo}}</td>
                        <td>{{$dataEstima->montoOctavoPrestamo}}</td>
                        <td>{{$dataEstima->totalMonto}}</td>
                        <td>{{$dataEstima->totalAbonos}}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <div>
            <table>
                <thead>
                    <tr>
                        <th>Horario</th>
                        <th>Miercoles</th>
                        <th>150</th>
                        <th>$</th>
                        <th>200</th>
                        <th>$</th>
                        <th>250</th>
                        <th>$</th>
                        <th>300</th>
                        <th>$</th>
                        <th>350</th>
                        <th>$</th>
                        <th>400</th>
                        <th>$</th>
                        <th>450</th>
                        <th>$</th>
                        <th>500</th>
                        <th>$</th>
                        <th>Total</th>
                        <th>TA</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($miercoles as $dataEstima)
                    <tr>
                        <td></td>
                        <td>{{$dataEstima->nombreMunicipio}}</td>
                        <td>{{$dataEstima->nPrimerPrestamo}}</td>
                        <td>{{$dataEstima->montoPrimerPrestamo}}</td>
                        <td>{{$dataEstima->nSegundoPrestamo}}</td>
                        <td>{{$dataEstima->montoSegundoPrestamo}}</td>
                        <td>{{$dataEstima->nTercerPrestamo}}</td>
                        <td>{{$dataEstima->montoTercerPrestamo}}</td>
                        <td>{{$dataEstima->nCuartoPrestamo}}</td>
                        <td>{{$dataEstima->montoCuartoPrestamo}}</td>
                        <td>{{$dataEstima->nQuintoPrestamo}}</td>
                        <td>{{$dataEstima->montoQuintoPrestamo}}</td>
                        <td>{{$dataEstima->nSextoPrestamo}}</td>
                        <td>{{$dataEstima->montoSextoPrestamo}}</td>
                        <td>{{$dataEstima->nSeptimoPrestamo}}</td>
                        <td>{{$dataEstima->montoSeptimoPrestamo}}</td>
                        <td>{{$dataEstima->nOctavoPrestamo}}</td>
                        <td>{{$dataEstima->montoOctavoPrestamo}}</td>
                        <td>{{$dataEstima->totalMonto}}</td>
                        <td>{{$dataEstima->totalAbonos}}</td>
                    </tr>
                    @endforeach
                    <tr>
                        <td></td>
                        <td>Totales</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div>
            <table>
                <thead>
                    <tr>
                        <th>Horario</th>
                        <th>Jueves</th>
                        <th>150</th>
                        <th>$</th>
                        <th>200</th>
                        <th>$</th>
                        <th>250</th>
                        <th>$</th>
                        <th>300</th>
                        <th>$</th>
                        <th>350</th>
                        <th>$</th>
                        <th>400</th>
                        <th>$</th>
                        <th>450</th>
                        <th>$</th>
                        <th>500</th>
                        <th>$</th>
                        <th>Total</th>
                        <th>TA</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($jueves as $dataEstima)
                    <tr>
                        <td></td>
                        <td>{{$dataEstima->nombreMunicipio}}</td>
                        <td>{{$dataEstima->nPrimerPrestamo}}</td>
                        <td>{{$dataEstima->montoPrimerPrestamo}}</td>
                        <td>{{$dataEstima->nSegundoPrestamo}}</td>
                        <td>{{$dataEstima->montoSegundoPrestamo}}</td>
                        <td>{{$dataEstima->nTercerPrestamo}}</td>
                        <td>{{$dataEstima->montoTercerPrestamo}}</td>
                        <td>{{$dataEstima->nCuartoPrestamo}}</td>
                        <td>{{$dataEstima->montoCuartoPrestamo}}</td>
                        <td>{{$dataEstima->nQuintoPrestamo}}</td>
                        <td>{{$dataEstima->montoQuintoPrestamo}}</td>
                        <td>{{$dataEstima->nSextoPrestamo}}</td>
                        <td>{{$dataEstima->montoSextoPrestamo}}</td>
                        <td>{{$dataEstima->nSeptimoPrestamo}}</td>
                        <td>{{$dataEstima->montoSeptimoPrestamo}}</td>
                        <td>{{$dataEstima->nOctavoPrestamo}}</td>
                        <td>{{$dataEstima->montoOctavoPrestamo}}</td>
                        <td>{{$dataEstima->totalMonto}}</td>
                        <td>{{$dataEstima->totalAbonos}}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        
        <div>
            <table>
                <thead>
                    <tr>
                        <th>Horario</th>
                        <th>Viernes</th>
                        <th>150</th>
                        <th>$</th>
                        <th>200</th>
                        <th>$</th>
                        <th>250</th>
                        <th>$</th>
                        <th>300</th>
                        <th>$</th>
                        <th>350</th>
                        <th>$</th>
                        <th>400</th>
                        <th>$</th>
                        <th>450</th>
                        <th>$</th>
                        <th>500</th>
                        <th>$</th>
                        <th>Total</th>
                        <th>TA</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($viernes as $dataEstima)
                    <tr>
                        <td></td>
                        <td>{{$dataEstima->nombreMunicipio}}</td>
                        <td>{{$dataEstima->nPrimerPrestamo}}</td>
                        <td>{{$dataEstima->montoPrimerPrestamo}}</td>
                        <td>{{$dataEstima->nSegundoPrestamo}}</td>
                        <td>{{$dataEstima->montoSegundoPrestamo}}</td>
                        <td>{{$dataEstima->nTercerPrestamo}}</td>
                        <td>{{$dataEstima->montoTercerPrestamo}}</td>
                        <td>{{$dataEstima->nCuartoPrestamo}}</td>
                        <td>{{$dataEstima->montoCuartoPrestamo}}</td>
                        <td>{{$dataEstima->nQuintoPrestamo}}</td>
                        <td>{{$dataEstima->montoQuintoPrestamo}}</td>
                        <td>{{$dataEstima->nSextoPrestamo}}</td>
                        <td>{{$dataEstima->montoSextoPrestamo}}</td>
                        <td>{{$dataEstima->nSeptimoPrestamo}}</td>
                        <td>{{$dataEstima->montoSeptimoPrestamo}}</td>
                        <td>{{$dataEstima->nOctavoPrestamo}}</td>
                        <td>{{$dataEstima->montoOctavoPrestamo}}</td>
                        <td>{{$dataEstima->totalMonto}}</td>
                        <td>{{$dataEstima->totalAbonos}}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>